#!/bin/sh

riverctl map normal Super+Shift Q close
riverctl map normal Super+Shift E exit

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous 

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous 

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
    riverctl map normal Super+Control $i toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super F toggle-fullscreen

riverctl declare-mode passthrough

riverctl map normal Super F11 enter-mode passthrough

riverctl map passthrough Super F11 enter-mode normal

riverctl set-repeat 50 500

riverctl rule-add -app-id 'float*' float
riverctl rule-add -app-id "bar" csd

riverctl map normal Super Return spawn alacritty
riverctl map normal Super Space spawn "~/.config/venv/bin/python3 ~/.config/fimon/app_launcher.py"

riverctl map normal Super P spawn 'grim -o ~/Downloads -g "$(slurp)" - | wl-copy'

riverctl border-width 0

swaybg -i ~/Wallpapers/some-wallpaper.png &
~/.config/venv/bin/python3 ~/.config/fibar/bar.py &
